import { Tone, Depth, Topic } from '@/types';

export interface CuratedQuestion {
  id: string;
  text: string;
  tones: Tone[];
  depth: Depth;
  topics: Topic[];
  timeLength: '2min' | '5min' | '10min';
}

export const CURATED_QUESTIONS: CuratedQuestion[] = [
  // FUNNY + SURFACE (Quick laughs - 20 questions)
  {
    id: 'q1',
    text: "What's a hill you're irrationally willing to die on?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q2',
    text: "If you could only eat one food for the rest of your life, what would it be?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q3',
    text: "What's the weirdest talent or skill you have?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q4',
    text: "If you were a kitchen appliance, which one would you be and why?",
    tones: ['funny'],
    depth: 'surface',
    topics: ['creative'],
    timeLength: '2min',
  },
  {
    id: 'q5',
    text: "What's your most embarrassing autocorrect fail?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q6',
    text: "What emoji best describes your week so far?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q7',
    text: "If you could be any fictional character for a day, who would it be?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q8',
    text: "What's the strangest thing you've ever eaten?",
    tones: ['funny'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q9',
    text: "If you could have any superpower but it had to be completely useless, what would it be?",
    tones: ['funny'],
    depth: 'surface',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q10',
    text: "What's your go-to karaoke song?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q11',
    text: "If you could swap lives with any animal for a day, which one?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q12',
    text: "What's the most ridiculous thing you believed as a child?",
    tones: ['funny'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q13',
    text: "If you had to wear one Halloween costume for the rest of your life, what would it be?",
    tones: ['funny'],
    depth: 'surface',
    topics: ['creative'],
    timeLength: '2min',
  },
  {
    id: 'q14',
    text: "What's your most unpopular food opinion?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q15',
    text: "If you could instantly become an expert at one random skill, what would it be?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q16',
    text: "What's the weirdest compliment you've ever received?",
    tones: ['funny'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q17',
    text: "If you could rename yourself, what name would you choose?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['creative', 'personal'],
    timeLength: '2min',
  },
  {
    id: 'q18',
    text: "What's the most useless thing you're really good at?",
    tones: ['funny'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q19',
    text: "If you could only communicate using GIFs for a day, which three would you choose?",
    tones: ['funny'],
    depth: 'surface',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q20',
    text: "What's the worst haircut you've ever had?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },

  // LIGHT + SURFACE (Easy warmups - 25 questions)
  {
    id: 'q21',
    text: "What's your go-to comfort snack?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q22',
    text: "What's the last show you binge-watched?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q23',
    text: "Coffee, tea, or neither?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q24',
    text: "What's your favorite way to spend a lazy Sunday?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q25',
    text: "If you could travel anywhere right now, where would you go?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal', 'creative'],
    timeLength: '5min',
  },
  {
    id: 'q26',
    text: "What's your phone background right now?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q27',
    text: "Are you a morning person or a night owl?",
    tones: ['light'],
    depth: 'surface',
    topics: ['work', 'personal'],
    timeLength: '2min',
  },
  {
    id: 'q28',
    text: "What's the best concert or live event you've ever been to?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q29',
    text: "What's your favorite season and why?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q30',
    text: "What app do you use most on your phone?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q31',
    text: "What's your comfort movie or show?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q32',
    text: "Beach vacation or mountain getaway?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q33',
    text: "What's your favorite type of music to listen to while working?",
    tones: ['light'],
    depth: 'surface',
    topics: ['work', 'personal'],
    timeLength: '2min',
  },
  {
    id: 'q34',
    text: "What's the best meal you've had recently?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q35',
    text: "If you could learn any language instantly, which would you choose?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal', 'creative'],
    timeLength: '2min',
  },
  {
    id: 'q36',
    text: "What's your favorite holiday?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q37',
    text: "Do you prefer hot weather or cold weather?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q38',
    text: "What's your favorite way to exercise?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q39',
    text: "What's a place that feels like home to you?",
    tones: ['light', 'thoughtful'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q40',
    text: "What's your favorite thing to cook or bake?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q41',
    text: "What's your favorite board game or card game?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q42',
    text: "What's your favorite childhood memory?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q43',
    text: "What's something you're looking forward to?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q44',
    text: "What's your favorite way to unwind after a long day?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q45',
    text: "What's one thing on your bucket list?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal', 'reflective'],
    timeLength: '5min',
  },

  // LIGHT + THOUGHTFUL + MEDIUM (Core icebreakers - 35 questions)
  {
    id: 'q46',
    text: "What's a small thing that instantly improves your day?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q47',
    text: "What's one thing you're trying to get better at right now?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q48',
    text: "What's a tradition from your childhood you still keep?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q49',
    text: "How do you recharge after a long day of work?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q50',
    text: "What's a book, podcast, or article that stuck with you?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q51',
    text: "What's a skill you'd love to learn if you had unlimited time?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q52',
    text: "What's your ideal work environment?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q53',
    text: "What's a creative outlet you have or wish you had?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q54',
    text: "If you could have dinner with anyone, living or dead, who would it be?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q55',
    text: "What's something you taught yourself that you're proud of?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q56',
    text: "What's a memory that always makes you smile?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q57',
    text: "What's the best advice you've ever received?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q58',
    text: "Who's someone you've learned a lot from?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective'],
    timeLength: '5min',
  },
  {
    id: 'q59',
    text: "What's the best thing you learned last year?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective'],
    timeLength: '5min',
  },
  {
    id: 'q60',
    text: "What's something you've changed your mind about recently?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective'],
    timeLength: '5min',
  },
  {
    id: 'q61',
    text: "What's a problem you wish someone would solve?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['creative', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q62',
    text: "If you could add one feature to any product you use daily, what would it be?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative', 'work'],
    timeLength: '5min',
  },
  {
    id: 'q63',
    text: "How do you prefer to brainstorm—alone first, or with others?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['work', 'creative'],
    timeLength: '5min',
  },
  {
    id: 'q64',
    text: "What's something that surprised you about working on this team?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q65',
    text: "What's your superpower at work?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q66',
    text: "What's something you wish you knew when you first started your career?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective', 'work'],
    timeLength: '5min',
  },
  {
    id: 'q67',
    text: "What's a recent challenge you overcame?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q68',
    text: "What's your favorite way to celebrate wins, big or small?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal', 'work'],
    timeLength: '5min',
  },
  {
    id: 'q69',
    text: "What's something you're curious about right now?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'creative'],
    timeLength: '5min',
  },
  {
    id: 'q70',
    text: "What hobby or interest would you love to explore more?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q71',
    text: "What's a piece of technology that genuinely improved your life?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q72',
    text: "What's your approach when you're feeling stuck or unmotivated?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['work', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q73',
    text: "What's something unexpected that you're grateful for?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q74',
    text: "What's a random act of kindness you witnessed or experienced recently?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q75',
    text: "What's your favorite way to learn new things?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'work'],
    timeLength: '5min',
  },
  {
    id: 'q76',
    text: "What's something small that made a big difference in your routine?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['personal', 'work'],
    timeLength: '5min',
  },
  {
    id: 'q77',
    text: "What's a place you've visited that changed your perspective?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q78',
    text: "What's your go-to method for staying organized?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q79',
    text: "What's something you wish more people knew about your job or industry?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q80',
    text: "What's a recent 'aha!' moment you had?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'work'],
    timeLength: '5min',
  },

  // THOUGHTFUL + SERIOUS + MEDIUM (Work-focused - 30 questions)
  {
    id: 'q81',
    text: "What kind of feedback helps you do your best work?",
    tones: ['thoughtful', 'serious'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q82',
    text: "What's one professional skill you wish you'd learned earlier?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['reflective', 'work'],
    timeLength: '5min',
  },
  {
    id: 'q83',
    text: "What does work-life balance mean to you?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['reflective', 'work'],
    timeLength: '10min',
  },
  {
    id: 'q84',
    text: "What's the most important thing you look for in a teammate?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q85',
    text: "What's your communication style when you're stuck on something?",
    tones: ['thoughtful', 'serious'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q86',
    text: "What's the most valuable lesson you've learned in your career so far?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q87',
    text: "What's your approach to giving feedback to others?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q88',
    text: "What do you need from your teammates to do your best work?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q89',
    text: "What's something about your role that people might not understand?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q90',
    text: "How do you prefer to collaborate on projects?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q91',
    text: "What's your biggest professional strength?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q92',
    text: "What's a skill you're actively working on developing?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q93',
    text: "What's your approach to prioritizing when everything feels urgent?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q94',
    text: "What kind of work energizes you the most?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q95',
    text: "What's something you wish your team did more of?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q96',
    text: "How do you know when you've done good work?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q97',
    text: "What's your strategy for managing stress at work?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q98',
    text: "What's the best professional advice you've received?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q99',
    text: "What's something you're proud of accomplishing this year?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q100',
    text: "What's your definition of a successful project?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q101',
    text: "How do you handle disagreements in the workplace?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q102',
    text: "What's a meeting you look forward to and why?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q103',
    text: "What aspect of your job would you want to teach someone else?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q104',
    text: "What's your process for making difficult decisions?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q105',
    text: "What keeps you engaged in your work?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q106',
    text: "What's the most useful feedback you've given someone recently?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q107',
    text: "What does a good working relationship look like to you?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q108',
    text: "How do you prefer to receive updates on projects?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q109',
    text: "What's a project you're excited to work on?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },
  {
    id: 'q110',
    text: "What would make you feel more supported in your role?",
    tones: ['serious', 'thoughtful'],
    depth: 'medium',
    topics: ['work'],
    timeLength: '5min',
  },

  // THOUGHTFUL + DEEP (Meaningful reflection - 35 questions)
  {
    id: 'q111',
    text: "What kind of work makes you feel most proud?",
    tones: ['thoughtful', 'serious'],
    depth: 'deep',
    topics: ['reflective', 'work'],
    timeLength: '10min',
  },
  {
    id: 'q112',
    text: "What's something that shaped how you see the world today?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q113',
    text: "What's a value you hold that you think is underrated?",
    tones: ['thoughtful', 'extreme'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q114',
    text: "What's something you wish more people understood about you?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['personal', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q115',
    text: "What does success look like for you in the next year?",
    tones: ['thoughtful', 'serious'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q116',
    text: "What motivates you when work gets hard?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'work'],
    timeLength: '10min',
  },
  {
    id: 'q117',
    text: "What's something from your past that taught you an important lesson?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q118',
    text: "What do you want your legacy to be?",
    tones: ['thoughtful', 'serious'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q119',
    text: "What's a personal philosophy or mantra you live by?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q120',
    text: "What does growth mean to you?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q121',
    text: "What's the most important relationship in your life and why?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['personal', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q122',
    text: "What makes you feel most alive?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q123',
    text: "What's something you're still figuring out about yourself?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q124',
    text: "What kind of person do you aspire to be?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q125',
    text: "What's a mistake that turned into something valuable?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q126',
    text: "What do you think is your purpose or calling?",
    tones: ['thoughtful', 'serious'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q127',
    text: "What's something you've had to unlearn?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q128',
    text: "What does happiness mean to you?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q129',
    text: "What's a dream you have for your future self?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q130',
    text: "What sacrifice have you made that you're proud of?",
    tones: ['thoughtful', 'serious'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q131',
    text: "What does courage look like to you?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q132',
    text: "What's an assumption about you that's wrong?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['personal', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q133',
    text: "What makes you feel most connected to others?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q134',
    text: "What's something you're working on accepting about yourself?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q135',
    text: "What does authenticity mean to you?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q136',
    text: "What's a belief you held strongly that has evolved?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q137',
    text: "What gives your life meaning?",
    tones: ['thoughtful', 'serious'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q138',
    text: "What's the hardest decision you've had to make?",
    tones: ['thoughtful', 'serious'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q139',
    text: "What do you hope people remember about you?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q140',
    text: "What role does creativity play in your life?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'creative'],
    timeLength: '10min',
  },
  {
    id: 'q141',
    text: "What's something you're passionate about that surprises people?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['personal', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q142',
    text: "What does vulnerability mean to you?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q143',
    text: "What's a quality you admire in others that you want to develop?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q144',
    text: "What's your relationship with failure?",
    tones: ['thoughtful', 'serious'],
    depth: 'deep',
    topics: ['reflective', 'work'],
    timeLength: '10min',
  },
  {
    id: 'q145',
    text: "What impact do you want to have on the world?",
    tones: ['thoughtful', 'serious'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },

  // EXTREME + DEEP (Bold, vulnerable - 25 questions)
  {
    id: 'q146',
    text: "What belief do you hold that most people disagree with?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q147',
    text: "What's something you think is broken in how we work today?",
    tones: ['extreme', 'serious'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q148',
    text: "What would you do differently if you were starting your career today?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q149',
    text: "What's a hard truth you've had to accept?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q150',
    text: "What's something people should talk about more openly?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q151',
    text: "What fear holds you back the most?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q152',
    text: "What's something you pretend to care about but don't really?",
    tones: ['extreme'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q153',
    text: "What industry norm or standard do you think needs to change?",
    tones: ['extreme', 'serious'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q154',
    text: "What's the most controversial opinion you hold?",
    tones: ['extreme'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q155',
    text: "What's something you know is true but wish wasn't?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q156',
    text: "What part of yourself do you hide from others?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['personal', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q157',
    text: "What would you change about society if you had the power?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q158',
    text: "What's a risk you wish you had taken?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q159',
    text: "What's something you're supposed to want but don't?",
    tones: ['extreme'],
    depth: 'deep',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q160',
    text: "What's a question you wish someone would ask you?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q161',
    text: "What privilege do you have that you think about?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q162',
    text: "What do you think people get wrong about your generation?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q163',
    text: "What's something you've done that you're not proud of but learned from?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q164',
    text: "What aspect of modern work culture frustrates you most?",
    tones: ['extreme', 'serious'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q165',
    text: "What would you do if you weren't afraid of judgment?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q166',
    text: "What's a double standard you notice in your industry or field?",
    tones: ['extreme', 'serious'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q167',
    text: "What conversation do you think your team needs to have?",
    tones: ['extreme', 'serious'],
    depth: 'deep',
    topics: ['work'],
    timeLength: '10min',
  },
  {
    id: 'q168',
    text: "What's something you've compromised on that you wish you hadn't?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q169',
    text: "What do you think people are afraid to admit to themselves?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q170',
    text: "What change would you make if you knew everyone would support it?",
    tones: ['extreme', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },

  // CREATIVE FOCUSED (Imagination & ideas - 35 questions)
  {
    id: 'q171',
    text: "If you could invent a new holiday, what would it celebrate?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q172',
    text: "If you could swap jobs with anyone for a day, who would it be?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q173',
    text: "If your life was a movie, what would the soundtrack be?",
    tones: ['light', 'creative'],
    depth: 'surface',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q174',
    text: "If you could design your dream office space, what would it look like?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative', 'work'],
    timeLength: '5min',
  },
  {
    id: 'q175',
    text: "If you could create a new app, what problem would it solve?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['creative', 'work'],
    timeLength: '5min',
  },
  {
    id: 'q176',
    text: "What would you do with a completely free Saturday?",
    tones: ['light'],
    depth: 'surface',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q177',
    text: "If you could have any fictional technology, what would you choose?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q178',
    text: "If you could master any art form instantly, what would it be?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q179',
    text: "What's your idea of a perfect day?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q180',
    text: "If you could redesign one common object, what would you change?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q181',
    text: "If you could live in any time period, when would it be?",
    tones: ['light'],
    depth: 'surface',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q182',
    text: "What's a business or product you wish existed?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q183',
    text: "If you could add one rule to any game or sport, what would it be?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q184',
    text: "What's your dream creative project?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q185',
    text: "If you could combine two animals into one, what would you create?",
    tones: ['funny'],
    depth: 'surface',
    topics: ['creative'],
    timeLength: '2min',
  },
  {
    id: 'q186',
    text: "What's an unconventional solution to a common problem?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q187',
    text: "If you could rename your job title to anything, what would it be?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['creative', 'work'],
    timeLength: '5min',
  },
  {
    id: 'q188',
    text: "What's a tradition you'd like to start?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q189',
    text: "If you could design a new emoji, what would it be?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['creative'],
    timeLength: '2min',
  },
  {
    id: 'q190',
    text: "What's your idea for improving meetings?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['creative', 'work'],
    timeLength: '5min',
  },
  {
    id: 'q191',
    text: "If you could write a book, what would it be about?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q192',
    text: "What's something you'd like to see more of in the world?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['creative', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q193',
    text: "If you could have a conversation with your future self, what would you ask?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['creative', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q194',
    text: "What's an innovation you're excited about?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q195',
    text: "If you could instantly become an expert in any field outside your own, what would it be?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q196',
    text: "What's a collaboration you'd love to see happen?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q197',
    text: "If you could start a podcast, what would it be about?",
    tones: ['light'],
    depth: 'surface',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q198',
    text: "What's your most ambitious daydream?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['creative', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q199',
    text: "If you could curate a museum exhibit, what would the theme be?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q200',
    text: "What's an idea that keeps coming back to you?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['creative', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q201',
    text: "If you could create a new genre of anything, what would it be?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q202',
    text: "What's a wild idea you have that might actually work?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['creative'],
    timeLength: '5min',
  },
  {
    id: 'q203',
    text: "If you could teach a masterclass on anything, what would it be?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q204',
    text: "What's something you'd like to experiment with?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q205',
    text: "If you could solve one mystery, what would it be?",
    tones: ['light'],
    depth: 'surface',
    topics: ['creative'],
    timeLength: '5min',
  },

  // SERIOUS + SERIOUS (Professional depth - 25 questions)
  {
    id: 'q206',
    text: "What's your definition of leadership?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q207',
    text: "What does excellence mean to you in your work?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q208',
    text: "What's the biggest challenge facing your industry right now?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work'],
    timeLength: '10min',
  },
  {
    id: 'q209',
    text: "How do you define professional integrity?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q210',
    text: "What's the most important responsibility you have in your role?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work'],
    timeLength: '10min',
  },
  {
    id: 'q211',
    text: "What kind of impact do you want your work to have?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q212',
    text: "What's a principle you won't compromise on professionally?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q213',
    text: "How do you balance stakeholder needs with your own judgment?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work'],
    timeLength: '10min',
  },
  {
    id: 'q214',
    text: "What ethical dilemma have you faced in your work?",
    tones: ['serious', 'extreme'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q215',
    text: "What makes a project truly successful beyond the metrics?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q216',
    text: "What responsibility do you think we have to future generations in our work?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q217',
    text: "How do you ensure your work aligns with your values?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q218',
    text: "What's the most important question to ask before starting a project?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work'],
    timeLength: '10min',
  },
  {
    id: 'q219',
    text: "What does accountability look like in practice?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work'],
    timeLength: '10min',
  },
  {
    id: 'q220',
    text: "How do you measure the value of your contributions?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q221',
    text: "What's a tough conversation your industry needs to have?",
    tones: ['serious', 'extreme'],
    depth: 'deep',
    topics: ['work'],
    timeLength: '10min',
  },
  {
    id: 'q222',
    text: "How do you want to grow as a professional in the next five years?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q223',
    text: "What's your approach to continuous improvement?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q224',
    text: "What does professional growth mean beyond title or salary?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q225',
    text: "What legacy do you want to leave in your field?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q226',
    text: "How do you ensure diverse perspectives are heard in your work?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work'],
    timeLength: '10min',
  },
  {
    id: 'q227',
    text: "What's the difference between being busy and being productive?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q228',
    text: "How do you balance innovation with proven methods?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work'],
    timeLength: '10min',
  },
  {
    id: 'q229',
    text: "What criteria do you use to decide what's worth your time?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },
  {
    id: 'q230',
    text: "What's your philosophy on work-life integration?",
    tones: ['serious', 'thoughtful'],
    depth: 'deep',
    topics: ['work', 'reflective'],
    timeLength: '10min',
  },

  // MIXED ADDITIONAL (Round out the collection - 58 questions)
  {
    id: 'q231',
    text: "What's the most useful thing someone taught you this month?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'work'],
    timeLength: '5min',
  },
  {
    id: 'q232',
    text: "What's your favorite way to spend time with friends?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q233',
    text: "What's a skill everyone should learn?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective'],
    timeLength: '5min',
  },
  {
    id: 'q234',
    text: "What's your go-to stress relief activity?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q235',
    text: "What's the best gift you've ever received?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q236',
    text: "What's something you're naturally good at?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal', 'work'],
    timeLength: '5min',
  },
  {
    id: 'q237',
    text: "What's your favorite thing about where you live?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q238',
    text: "What's a documentary or movie that changed how you think?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q239',
    text: "What's your favorite childhood game?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q240',
    text: "What's something you wish you had more time for?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q241',
    text: "What's your favorite way to celebrate?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q242',
    text: "What's a quote or saying that resonates with you?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective'],
    timeLength: '5min',
  },
  {
    id: 'q243',
    text: "What's your ideal way to start the morning?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q244',
    text: "What's something that always makes you laugh?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q245',
    text: "What's a goal you're working toward right now?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q246',
    text: "What's your favorite way to be creative?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q247',
    text: "What's something you collect or wish you collected?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q248',
    text: "What's the longest you've ever stuck with a hobby?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q249',
    text: "What's your favorite local spot?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q250',
    text: "What's something you're proud of that others might not know about?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['personal', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q251',
    text: "What's your comfort food?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q252',
    text: "What's the best compliment you've ever received?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q253',
    text: "What's your go-to conversation starter?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q254',
    text: "What's something you're looking forward to learning?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q255',
    text: "What's your favorite time of day?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q256',
    text: "What's a simple pleasure you really enjoy?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q257',
    text: "What's your hidden talent?",
    tones: ['funny', 'light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q258',
    text: "What's something that's harder than it looks?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['work', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q259',
    text: "What's your favorite thing to do on a Friday night?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q260',
    text: "What's something that gives you energy?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q261',
    text: "What's a trend you're into right now?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q262',
    text: "What's your go-to way to help someone?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q263',
    text: "What's the best meal you know how to cook?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q264',
    text: "What's a subject you could talk about for hours?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q265',
    text: "What's your ideal weekend activity?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q266',
    text: "What's something you do to take care of yourself?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['personal', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q267',
    text: "What's your favorite way to spend a rainy day?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q268',
    text: "What's a habit you're trying to build?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q269',
    text: "What's your favorite type of weather?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q270',
    text: "What's something that surprised you about adulthood?",
    tones: ['funny', 'thoughtful'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q271',
    text: "What's your favorite nostalgic memory?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q272',
    text: "What's something you do differently than most people?",
    tones: ['light', 'funny'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q273',
    text: "What's your favorite type of food or cuisine?",
    tones: ['light'],
    depth: 'surface',
    topics: ['personal'],
    timeLength: '2min',
  },
  {
    id: 'q274',
    text: "What's something you appreciate more now than you used to?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q275',
    text: "What's your earliest memory?",
    tones: ['light', 'thoughtful'],
    depth: 'medium',
    topics: ['personal'],
    timeLength: '5min',
  },
  {
    id: 'q276',
    text: "What's something you're grateful for today?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q277',
    text: "What's your favorite way to connect with people?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['personal', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q278',
    text: "What's something you find beautiful?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['personal', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q279',
    text: "What's a piece of advice you'd give your younger self?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q280',
    text: "What's your favorite thing about your current life stage?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q281',
    text: "What's something you wish you could tell everyone?",
    tones: ['thoughtful', 'extreme'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q282',
    text: "What does home mean to you?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q283',
    text: "What's your relationship with change?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective'],
    timeLength: '10min',
  },
  {
    id: 'q284',
    text: "What helps you feel grounded?",
    tones: ['thoughtful'],
    depth: 'medium',
    topics: ['reflective', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q285',
    text: "What's something you hope never changes?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['personal', 'reflective'],
    timeLength: '5min',
  },
  {
    id: 'q286',
    text: "What's your favorite way to express yourself?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['creative', 'personal'],
    timeLength: '5min',
  },
  {
    id: 'q287',
    text: "What makes you feel most like yourself?",
    tones: ['thoughtful'],
    depth: 'deep',
    topics: ['reflective', 'personal'],
    timeLength: '10min',
  },
  {
    id: 'q288',
    text: "What's a question you love being asked?",
    tones: ['thoughtful', 'light'],
    depth: 'medium',
    topics: ['personal', 'reflective'],
    timeLength: '5min',
  },
];
